// lionsmane-fe/src/components/article-card.tsx
import { Link } from '@tanstack/react-router';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from './ui/card';
import type { ArticleDetail } from '@/types/article';
import { $api } from '@/lib/fetch-client';
import { toast } from 'sonner';
import { Badge } from '@/components/ui/badge';
import SolarStarBold from '~icons/solar/star-bold';
import SolarStarLinear from '~icons/solar/star-linear';
import { Button } from './ui/button';
import { format } from 'date-fns';
import { useQueryClient } from '@tanstack/react-query';

function ReadBadge({ read }: { read: boolean }) {
  if (read) {
    return <Badge variant="secondary">Read</Badge>;
  } else {
    return <Badge variant="default">Unread</Badge>;
  }
}

export function ArticleCard({ article }: { article: ArticleDetail }) {
  const { mutate, error } = $api.useMutation('patch', '/article/status/{id}', {
    onSuccess: async () => {
      await queryClient.invalidateQueries({
        queryKey: ['get', '/article/unread'],
      });
      await queryClient.invalidateQueries({
        queryKey: ['get', '/article/read'],
      });
      await queryClient.invalidateQueries({
        queryKey: ['get', '/article/starred'],
      });
    },
  });
  const queryClient = useQueryClient();

  if (error) {
    toast.error('Error marking article as read');
  }

  const articleFeed =
    article.feedTitle.length > 50
      ? article.feedTitle.slice(0, 50) + '...'
      : article.feedTitle;

  function markStarred() {
    mutate({
      params: {
        path: {
          id: article.id,
        },
        query: {
          status: 'starred',
        },
      },
      credentials: 'include',
    });
  }
  function markUnstarred() {
    mutate({
      params: {
        path: {
          id: article.id,
        },
        query: {
          status: 'unstarred',
        },
      },
    });
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>
          <Link
            to="/dashboard/$articleId"
            params={{ articleId: article.id }}
            onClick={() =>
              mutate({
                params: {
                  path: {
                    id: article.id,
                  },
                  query: {
                    status: 'read',
                  },
                },
                credentials: 'include',
              })
            }
          >
            {article.title}
          </Link>
          <div className="justify">
            <ReadBadge read={article.isRead || false} />
            <Badge variant="outline">{articleFeed}</Badge>
            {!article.isStarred && (
              <Button variant="ghost" size="icon" onClick={markStarred}>
                <SolarStarLinear />
              </Button>
            )}
            {article.isStarred && (
              <Button variant="ghost" size="icon" onClick={markUnstarred}>
                <SolarStarBold />
              </Button>
            )}
          </div>
        </CardTitle>
        <CardDescription>
          {format(new Date(article.published), 'MMM d, yyyy HH:mm')}
        </CardDescription>
      </CardHeader>
      <CardContent>{article.readableText?.slice(0, 150) + '...'}</CardContent>
    </Card>
  );
}

// lionsmane-fe/app/components/ArticleCard.vue
<!--
  - Copyright (c) 2025 Margaret Miller.  Licensed under the EUPL-1.2-or-later.
  -->

<script setup lang="ts">
const { articlePreview } = defineProps<{
  articlePreview: {
    id: string;
    title: string;
    preview: string | undefined;
    date: string;
    isRead: boolean;
    starred: boolean;
  };
}>();

const toast = useToast();
const queryClient = useQueryClient();

type ArticleStarring = {
  id: string;
  starred: boolean;
};
const { isError, error, isSuccess, mutate } = useMutation({
  mutationFn: (art: ArticleStarring) =>
    $lion('/articles/{id}', {
      method: 'PATCH',
      path: {
        id: art.id,
      },
      body: {
        starred: art.starred,
      },
    }),
  onSuccess: async () => {
    await queryClient.invalidateQueries({ queryKey: ['articles'] });
  },
  onError: () => {
    toast.add({ title: 'Error setting article as read', color: 'error' });
  },
  retry: 3,
});

function onStar() {
  mutate({
    id: articlePreview.id,
    starred: true,
  });
}
function onUnStar() {
  mutate({
    id: articlePreview.id,
    starred: false,
  });
}
</script>

<template>
  <Card>
    <CardHeader>
      <CardTitle>
        <NuxtLink
          :to="{
            name: 'dashboard-articles-id',
            params: { id: articlePreview.id },
          }"
        >
          {{ articlePreview.title }}
        </NuxtLink>
        <div class="">
          <div v-show="articlePreview.isRead === false">
            <UBadge icon="radix-icons:dot-filled" color="info">Unread</UBadge>
          </div>
          <UButton
            v-if="articlePreview.starred === true"
            icon="i-fluent-star-12-filled"
            variant="ghost"
            @click="onUnStar"
          />
          <UButton
            v-else-if="articlePreview.starred === false"
            icon="i-fluent-star-12-regular"
            variant="ghost"
            @click="onStar"
          />
        </div>
      </CardTitle>
    </CardHeader>
    <CardContent>
      <div class="flex-1">
        <p class="mt-1">{{ articlePreview.preview }}</p>
      </div>
    </CardContent>
    <CardFooter>
      {{ new Date(articlePreview.date).toLocaleDateString() }}
    </CardFooter>
  </Card>
</template>
