// lionsmane-fe/src/components/article-card.tsx
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import type { ArticleDetail } from '@/types/article';

export function ArticleCard({ article }: { article: ArticleDetail }) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>{article.title}</CardTitle>
      </CardHeader>
      <CardContent>{article.readableText?.slice(0, 150) + '...'}</CardContent>
    </Card>
  );
}

// lionsmane-fe/components/ArticleCard.vue
<script setup lang="ts">
defineProps<{
  articlePreview: {
    title: string,
    preview: string,
  }
}>()
</script>

<template>
  <Card>
    <CardTitle>
      {{articlePreview.title}}
    </CardTitle>
    <CardContent>
      <div class="flex-1">
        <p class="mt-1">{{articlePreview.preview}}</p>
      </div>
    </CardContent>
  </Card>

</template>
